name: Deploy Container to GitHub Container Registry

on:
  push:
    branches:
      - Testing

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
